application: bridge-demo
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /mocks/
  static_files: mocks/home.html
  upload: mocks/home.html
- url: /mocks
  static_dir: mocks
- url: /_/s
  static_dir: static
- url: .*
  script: main.app
  login: required

error_handlers:
  - file: templates/default_error.html

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
